<?php

namespace LemurAse;

use LemurAse\Application\UseCases\CreateOrder;
use LemurAse\Application\UseCases\ExpireStaleOrders;
use LemurAse\Application\UseCases\PriceCalculator;
use LemurAse\Application\UseCases\ProcessWebhook;
use LemurAse\Domain\Services\SecurityService;
use LemurAse\Infrastructure\Persistence\LemurOrderRepository;
use LemurAse\Infrastructure\Persistence\LemurPlanPriceRepository;
use LemurAse\Infrastructure\Persistence\LemurCustomPriceRepository;
use LemurAse\Infrastructure\Persistence\LemurSubscriptionRepository;
use LemurAse\Infrastructure\Persistence\LemurInvoiceRepository;
use LemurAse\Infrastructure\Persistence\LemurTransactionLogRepository;
use LemurAse\Infrastructure\Payments\StripeAdapter;
use LemurAse\Infrastructure\Payments\PayPalAdapter;
use LemurAse\Domain\ValueObjects\EntityId;

final class AseManager
{
    private static ?self $instance = null;

    // Repositories
    private LemurOrderRepository $orderRepo;
    private LemurPlanPriceRepository $planPriceRepo;
    private LemurCustomPriceRepository $customPriceRepo;
    private LemurSubscriptionRepository $subscriptionRepo;
    private LemurInvoiceRepository $invoiceRepo;
    private LemurTransactionLogRepository $logRepo;

    // Services
    private SecurityService $securityService;
    private PriceCalculator $priceCalculator;

    private function __construct()
    {
        $this->orderRepo = new LemurOrderRepository();
        $this->planPriceRepo = new LemurPlanPriceRepository();
        $this->customPriceRepo = new LemurCustomPriceRepository();
        $this->subscriptionRepo = new LemurSubscriptionRepository();
        $this->invoiceRepo = new LemurInvoiceRepository();
        $this->logRepo = new LemurTransactionLogRepository();

        $this->securityService = new SecurityService();
        $this->priceCalculator = new PriceCalculator($this->customPriceRepo);
    }

    public static function getInstance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Initialize a checkout session.
     */
    public static function createCheckoutSession(string $clientId, string $planPriceId, string $gatewayId): string
    {
        $manager = self::getInstance();
        $useCase = new CreateOrder(
            $manager->orderRepo, 
            $manager->planPriceRepo, 
            $manager->priceCalculator, 
            $manager->securityService
        );

        $order = $useCase->execute($clientId, $planPriceId, $gatewayId);

        // Fetch the corresponding gateway adapter dynamically
        // In a real implementation, you might fetch the gateway record from DB
        // Here we simulate for Stripe/PayPal
        $gatewayProvider = 'stripe'; // This would be fetched from DB via $gatewayId
        $adapter = $manager->getGatewayAdapter($gatewayProvider);
        
        $session = $adapter->createCheckoutSession($order);

        // Save external order ID generated by the gateway
        $orderReflection = new \ReflectionClass($order);
        $property = $orderReflection->getProperty('externalOrderId');
        $property->setAccessible(true);
        $property->setValue($order, $session['external_id']);
        
        $manager->orderRepo->save($order);

        return $session['checkout_url'];
    }

    /**
     * Expire stale orders. Intended for a cron job.
     */
    public static function expireStaleOrders(): int
    {
        $manager = self::getInstance();
        $useCase = new ExpireStaleOrders($manager->orderRepo);
        return $useCase->execute();
    }

    /**
     * Process an incoming webhook.
     */
    public static function handleWebhook(string $gatewayProvider, array $payload, array $headers): bool
    {
        $manager = self::getInstance();
        $adapter = $manager->getGatewayAdapter($gatewayProvider);

        if (!$adapter->validateWebhook($payload, $headers)) {
            throw new \RuntimeException("Invalid webhook signature.");
        }

        $eventData = $adapter->parseWebhookEvent($payload);

        // We only process 'paid' status for this demo
        if ($eventData['status'] !== 'paid') {
            return true; // Acknowledge non-payment events without action
        }

        $useCase = new ProcessWebhook(
            $manager->orderRepo,
            $manager->subscriptionRepo,
            $manager->invoiceRepo,
            $manager->logRepo,
            $manager->planPriceRepo
        );

        return $useCase->execute($eventData);
    }

    /**
     * Get the active subscription for a client.
     */
    public static function getClientActiveSubscription(string $clientId): ?array
    {
        $manager = self::getInstance();
        $subs = $manager->subscriptionRepo->findByClientAndStatus($clientId, 'active');
        
        if (empty($subs)) {
            return null;
        }

        // Return the first active one as array
        return $subs[0]; 
    }

    /**
     * Get client invoices.
     */
    public static function getClientInvoices(string $clientId, int $limit = 10): array
    {
        $manager = self::getInstance();
        $invoices = $manager->invoiceRepo->findByClient($clientId);
        
        // Simple manual limit
        return array_slice($invoices, 0, $limit);
    }

    /**
     * Helper to verify if the client has active access considering the grace period.
     */
    public static function hasActiveAccess(string $clientId, string $planSlug): bool
    {
        $manager = self::getInstance();
        
        // Find active or past_due subscriptions
        $subs = array_merge(
            $manager->subscriptionRepo->findByClientAndStatus($clientId, 'active'),
            $manager->subscriptionRepo->findByClientAndStatus($clientId, 'past_due')
        );

        if (empty($subs)) {
            return false;
        }

        foreach ($subs as $subData) {
            // Check if the plan matches (requires JOIN in a real scenario, but simplified here)
            // Assuming we check the end date + grace period
            $endDate = new \DateTimeImmutable($subData['current_period_end']);
            
            // Assuming 3 days grace period for past_due
            if ($subData['status'] === 'past_due') {
                $endDate = $endDate->modify('+3 days');
            }

            if ($endDate > new \DateTimeImmutable()) {
                return true;
            }
        }

        return false;
    }

    /**
     * Admin method to assign a custom price to a client.
     */
    public static function assignCustomPrice(string $clientId, string $planPriceId, float $amount, ?string $validUntil): void
    {
        $manager = self::getInstance();
        
        $data = [
            'id' => EntityId::generate()->uuid(),
            'short_id' => EntityId::generate()->short(),
            'plan_price_id' => $planPriceId,
            'external_client_id' => $clientId,
            'custom_amount' => $amount,
            'valid_until' => $validUntil
        ];

        // In a real scenario, this would use the CustomPriceRepository to save it.
        // As LemurCustomPriceRepository only has findByClientAndPlanPrice right now, 
        // we use the query builder directly for this demo.
        \LemurAse\Shared\LemurInstance::get()
            ->query(\LemurAse\Infrastructure\Persistence\TableNames::CUSTOM_PRICES)
            ->insert($data);
    }

    /**
     * Admin or user action to cancel a subscription.
     */
    public static function cancelSubscription(string $clientId, string $subscriptionId, bool $atPeriodEnd = true): void
    {
        $manager = self::getInstance();
        $sub = $manager->subscriptionRepo->findById(EntityId::fromString($subscriptionId));

        if (!$sub || $sub->externalClientId() !== $clientId) {
            throw new \InvalidArgumentException("Subscription not found or does not belong to client.");
        }

        // If not at period end, cancel immediately
        $status = $atPeriodEnd ? 'active' : 'canceled'; // Simplified
        $canceledAt = (new \DateTimeImmutable())->format('Y-m-d H:i:s');

        \LemurAse\Shared\LemurInstance::get()
            ->query(\LemurAse\Infrastructure\Persistence\TableNames::SUBSCRIPTIONS)
            ->where(['id' => $subscriptionId])
            ->update([
                'status' => $status,
                'canceled_at' => $canceledAt
            ]);
    }

    private function getGatewayAdapter(string $provider)
    {
        return match (strtolower($provider)) {
            'stripe' => new StripeAdapter(),
            'paypal' => new PayPalAdapter(),
            default => throw new \InvalidArgumentException("Unsupported gateway provider: {$provider}")
        };
    }
}
