<?php

namespace LemurAse;

use LemurAse\Application\UseCases\CreateOrder;
use LemurAse\Application\UseCases\ExpireStaleOrders;
use LemurAse\Application\UseCases\PriceCalculator;
use LemurAse\Application\UseCases\ProcessWebhook;
use LemurAse\Domain\Services\SecurityService;
use LemurAse\Infrastructure\Persistence\LemurOrderRepository;
use LemurAse\Infrastructure\Persistence\LemurPlanPriceRepository;
use LemurAse\Infrastructure\Persistence\LemurCustomPriceRepository;
use LemurAse\Infrastructure\Persistence\LemurSubscriptionRepository;
use LemurAse\Infrastructure\Persistence\LemurInvoiceRepository;
use LemurAse\Infrastructure\Persistence\LemurTransactionLogRepository;
use LemurAse\Infrastructure\Payments\StripeAdapter;
use LemurAse\Infrastructure\Payments\PayPalAdapter;
use LemurAse\Domain\ValueObjects\EntityId;

final class AseManager
{
    private static ?self $instance = null;

    // Repositories
    private LemurOrderRepository $orderRepo;
    private LemurPlanPriceRepository $planPriceRepo;
    private LemurCustomPriceRepository $customPriceRepo;
    private LemurSubscriptionRepository $subscriptionRepo;
    private LemurInvoiceRepository $invoiceRepo;
    private LemurTransactionLogRepository $logRepo;

    // Services
    private SecurityService $securityService;
    private PriceCalculator $priceCalculator;

    private function __construct()
    {
        $this->orderRepo = new LemurOrderRepository();
        $this->planPriceRepo = new LemurPlanPriceRepository();
        $this->customPriceRepo = new LemurCustomPriceRepository();
        $this->subscriptionRepo = new LemurSubscriptionRepository();
        $this->invoiceRepo = new LemurInvoiceRepository();
        $this->logRepo = new LemurTransactionLogRepository();

        $this->securityService = new SecurityService();
        $this->priceCalculator = new PriceCalculator($this->customPriceRepo);
    }

    public static function getInstance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Initialize a checkout session.
     */
    public static function createCheckoutSession(string $clientId, string $planPriceId, string $gatewayId): string
    {
        $manager = self::getInstance();
        $useCase = new CreateOrder(
            $manager->orderRepo, 
            $manager->planPriceRepo, 
            $manager->priceCalculator, 
            $manager->securityService
        );

        $order = $useCase->execute($clientId, $planPriceId, $gatewayId);

        // Fetch the corresponding gateway adapter dynamically
        // In a real implementation, you might fetch the gateway record from DB
        // Here we simulate for Stripe/PayPal
        $gatewayProvider = 'stripe'; // This would be fetched from DB via $gatewayId
        $adapter = $manager->getGatewayAdapter($gatewayProvider);
        
        $session = $adapter->createCheckoutSession($order);

        // Save external order ID generated by the gateway
        $orderReflection = new \ReflectionClass($order);
        $property = $orderReflection->getProperty('externalOrderId');
        $property->setAccessible(true);
        $property->setValue($order, $session['external_id']);
        
        $manager->orderRepo->save($order);

        return $session['checkout_url'];
    }

    /**
     * Expire stale orders. Intended for a cron job.
     */
    public static function expireStaleOrders(): int
    {
        $manager = self::getInstance();
        $useCase = new ExpireStaleOrders($manager->orderRepo);
        return $useCase->execute();
    }

    /**
     * Process an incoming webhook using the built-in adapter for validation.
     */
    public static function handleWebhook(string $gatewayProvider, array $payload, array $headers): bool
    {
        $manager = self::getInstance();
        $adapter = $manager->getGatewayAdapter($gatewayProvider);

        if (!$adapter->validateWebhook($payload, $headers)) {
            throw new \RuntimeException("Invalid webhook signature.");
        }

        $eventData = $adapter->parseWebhookEvent($payload);
        return self::processValidatedEvent($eventData['action'] ?? 'UNKNOWN', $eventData);
    }

    /**
     * Process a webhook event that has already been validated and parsed by the host system.
     * This is useful if the host uses official SDKs (like stripe-php) to construct the event.
     */
    public static function processValidatedEvent(string $action, array $normalizedData): bool
    {
        $manager = self::getInstance();

        // If the adapter or host didn't recognize the event as a standard action, ignore it
        if ($action === 'UNKNOWN' || $action === 'IGNORED') {
            return true; 
        }

        $useCase = new ProcessWebhook(
            $manager->orderRepo,
            $manager->subscriptionRepo,
            $manager->invoiceRepo,
            $manager->logRepo,
            $manager->planPriceRepo
        );

        return $useCase->execute($action, $normalizedData);
    }

    /**
     * Get the active subscription for a client.
     */
    public static function getClientActiveSubscription(string $clientId): ?array
    {
        $manager = self::getInstance();
        $subs = $manager->subscriptionRepo->findByClientAndStatus($clientId, 'active');
        
        if (empty($subs)) {
            return null;
        }

        // Return the first active one as array
        $sub = $subs[0];
        return [
            'id' => $sub->id()->uuid(),
            'order_id' => $sub->orderId()->uuid(),
            'external_client_id' => $sub->externalClientId(),
            'plan_price_id' => $sub->planPriceId()->uuid(),
            'gateway_id' => $sub->gatewayId()->uuid(),
            'status' => $sub->status(),
            'current_period_start' => $sub->currentPeriodStart()?->format('Y-m-d H:i:s'),
            'current_period_end' => $sub->currentPeriodEnd()?->format('Y-m-d H:i:s'),
            'canceled_at' => $sub->canceledAt()?->format('Y-m-d H:i:s'),
            'external_subscription_id' => $sub->externalSubscriptionId()
        ];
    }

    /**
     * Get client invoices.
     */
    public static function getClientInvoices(string $clientId, int $limit = 10): array
    {
        $manager = self::getInstance();
        $invoices = $manager->invoiceRepo->findByClient($clientId);
        
        $result = [];
        foreach (array_slice($invoices, 0, $limit) as $inv) {
            $result[] = [
                'id' => $inv->id()->uuid(),
                'order_id' => $inv->orderId()->uuid(),
                'subscription_id' => $inv->subscriptionId()?->uuid(),
                'external_client_id' => $inv->externalClientId(),
                'invoice_number' => $inv->invoiceNumber(),
                'subtotal' => $inv->subtotal(),
                'tax_amount' => $inv->taxAmount(),
                'total' => $inv->total()->amount(),
                'currency' => $inv->total()->currency()->toString(),
                'period_start' => $inv->periodStart()?->format('Y-m-d H:i:s'),
                'period_end' => $inv->periodEnd()?->format('Y-m-d H:i:s'),
                'status' => $inv->status(),
                'issued_at' => $inv->issuedAt()?->format('Y-m-d H:i:s'),
                'due_at' => $inv->dueAt()?->format('Y-m-d H:i:s'),
                'paid_at' => $inv->paidAt()?->format('Y-m-d H:i:s')
            ];
        }
        
        return $result;
    }

    /**
     * Helper to verify if the client has active access considering the grace period.
     */
    public static function hasActiveAccess(string $clientId, string $planSlug): bool
    {
        $manager = self::getInstance();
        
        // Find active or past_due subscriptions
        $subs = array_merge(
            $manager->subscriptionRepo->findByClientAndStatus($clientId, 'active'),
            $manager->subscriptionRepo->findByClientAndStatus($clientId, 'past_due')
        );

        if (empty($subs)) {
            return false;
        }

        foreach ($subs as $sub) {
            // Check if the plan matches (requires JOIN in a real scenario, but simplified here)
            // Assuming we check the end date + grace period
            $endDate = $sub->currentPeriodEnd();
            
            if (!$endDate) {
                if ($sub->status() === 'active') {
                    return true;
                }
                continue;
            }
            
            // Assuming 3 days grace period for past_due
            if ($sub->status() === 'past_due') {
                $endDate = $endDate->modify('+3 days');
            }

            if ($endDate > new \DateTimeImmutable()) {
                return true;
            }
        }

        return false;
    }

    /**
     * Admin method to assign a custom price to a client.
     */
    public static function assignCustomPrice(string $clientId, string $planPriceId, float $amount, ?string $validUntil): void
    {
        $manager = self::getInstance();
        
        $data = [
            'id' => EntityId::generate()->uuid(),
            'short_id' => EntityId::generate()->short(),
            'plan_price_id' => $planPriceId,
            'external_client_id' => $clientId,
            'custom_amount' => $amount,
            'valid_until' => $validUntil
        ];

        // In a real scenario, this would use the CustomPriceRepository to save it.
        // As LemurCustomPriceRepository only has findByClientAndPlanPrice right now, 
        // we use the query builder directly for this demo.
        \LemurAse\Shared\LemurInstance::get()
            ->query(\LemurAse\Infrastructure\Persistence\TableNames::CUSTOM_PRICES)
            ->insert($data);
    }

    /**
     * Admin or user action to cancel a subscription.
     */
    public static function cancelSubscription(string $clientId, string $subscriptionId, bool $atPeriodEnd = true): void
    {
        $manager = self::getInstance();
        $sub = $manager->subscriptionRepo->findById(EntityId::fromString($subscriptionId));

        if (!$sub || $sub->externalClientId() !== $clientId) {
            throw new \InvalidArgumentException("Subscription not found or does not belong to client.");
        }

        // If not at period end, cancel immediately
        $status = $atPeriodEnd ? 'active' : 'canceled'; // Simplified
        $canceledAt = (new \DateTimeImmutable())->format('Y-m-d H:i:s');

        \LemurAse\Shared\LemurInstance::get()
            ->query(\LemurAse\Infrastructure\Persistence\TableNames::SUBSCRIPTIONS)
            ->where(['id' => $subscriptionId])
            ->update([
                'status' => $status,
                'canceled_at' => $canceledAt
            ]);
    }

    private function getGatewayAdapter(string $provider)
    {
        return match (strtolower($provider)) {
            'stripe' => new StripeAdapter(),
            'paypal' => new PayPalAdapter(),
            default => throw new \InvalidArgumentException("Unsupported gateway provider: {$provider}")
        };
    }
}
